# -*- mode: ruby -*-
# vi: set ft=ruby :


ENV['VAGRANT_SERVER_URL'] = 'https://vagrant.elab.pro'

boxes = [
  { :name => "kernel-sources", :box => "centos/8", :memory => 32768, :cpus => 8,  :script => '~/admpro/hw1/compile.sh'},
  { :name => "kernel-update", :box => "centos/8", :memory => 8192, :cpus => 2, :script => '~/admpro/hw1/simple.sh' },    
 ]

Vagrant.configure("2") do |config|

  boxes.each do |box|
    config.vm.define box[:name] do |target|
      target.vm.provider "virtualbox" do |v|
        v.name = box[:name]
        v.memory = box[:memory]
        v.cpus = box[:cpus]
        v.customize ["modifyvm", :id, "--groups", "/ADV_HW"]
      end
      target.vm.disk :disk, size: "100GB", primary: true
      target.vm.box = box[:box]
      target.vm.communicator = "ssh"
      target.vm.hostname = box[:name]
      target.vm.provision "shell", path: box[:script]
      target.vm.provision "reboot", type: "shell", inline: "", reboot: true
    end
  end
end